In [106]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.grid_search import GridSearchCV
import sys
from datetime import datetime

In [107]:
train = pd.read_csv("./input/train.csv")
train

,AnimalID,Name,DateTime,OutcomeType,OutcomeSubtype,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color
0,A671945,Hambone,2014-02-12 18:22:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Shetland Sheepdog Mix,Brown/White
1,A656520,Emily,2013-10-13 12:44:00,Euthanasia,Suffering,Cat,Spayed Female,1 year,Domestic Shorthair Mix,Cream Tabby
2,A686464,Pearce,2015-01-31 12:28:00,Adoption,Foster,Dog,Neutered Male,2 years,Pit Bull Mix,Blue/White
3,A683430,NaN,2014-07-11 19:09:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Cream
4,A667013,NaN,2013-11-15 12:52:00,Transfer,Partner,Dog,Neutered Male,2 years,Lhasa Apso/Miniature Poodle,Tan
5,A677334,Elsa,2014-04-25 13:04:00,Transfer,Partner,Dog,Intact Female,1 month,Cairn Terrier/Chihuahua Shorthair,Black/Tan
6,A699218,Jimmy,2015-03-28 13:11:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Blue Tabby
7,A701489,NaN,2015-04-30 17:02:00,Transfer,Partner,Cat,Unknown,3 weeks,Domestic Shorthair Mix,Brown Tabby
8,A671784,Lucy,2014-02-04 17:17:00,Adoption,NaN,Dog,Spayed Female,5 months,American Pit Bull Terrier Mix,Red/White
9,A677747,NaN,2014-05-03 07:48:00,Adoption,Offsite,Dog,Spayed Female,1 year,Cairn Terrier,White
10,A668402,NaN,2013-12-05 15:50:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Black
11,A666320,NaN,2013-11-04 14:48:00,Adoption,NaN,Dog,Spayed Female,2 years,Miniature Schnauzer Mix,Silver
12,A684601,Rocket,2016-02-03 11:27:00,Adoption,Foster,Dog,Neutered Male,4 years,Pit Bull Mix,Brown
13,A704702,Scooter,2015-06-08 16:30:00,Return_to_owner,NaN,Dog,Neutered Male,2 years,Yorkshire Terrier Mix,Black/Red
14,A688584,Preston,2015-11-25 15:00:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Great Pyrenees Mix,White/Cream
15,A678825,Oliver,2014-07-12 12:10:00,Adoption,Foster,Cat,Neutered Male,3 months,Domestic Shorthair Mix,Orange Tabby/White
16,A678050,NaN,2014-05-03 16:15:00,Transfer,Partner,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby
17,A680028,NaN,2014-06-07 12:54:00,Transfer,Partner,Dog,Intact Female,2 weeks,Pit Bull Mix,Brown/White
18,A679010,Chrissy,2014-05-17 11:32:00,Transfer,Partner,Cat,Intact Female,2 years,Angora Mix,White
19,A684787,Kuma,2014-07-30 17:34:00,Return_to_owner,NaN,Dog,Neutered Male,1 year,Flat Coat Retriever Mix,Black
20,A670658,Anders,2014-01-19 15:03:00,Transfer,Partner,Dog,Intact Male,2 months,Queensland Heeler Mix,Black/White
21,A708812,Munchkin,2015-09-18 15:19:00,Transfer,Partner,Cat,Spayed Female,1 year,Domestic Shorthair Mix,White
22,A705262,Jamaica,2015-08-15 14:22:00,Adoption,NaN,Dog,Spayed Female,2 years,Plott Hound/Boxer,Brown Brindle/White
23,A665781,Quattro,2013-10-28 16:32:00,Adoption,NaN,Dog,Neutered Male,10 months,German Shepherd Mix,Brown/White
24,A676333,Trigger,2014-04-09 17:44:00,Return_to_owner,NaN,Dog,Neutered Male,2 months,German Shepherd Mix,Black/Brown
25,A712750,Olive,2015-10-03 15:44:00,Transfer,Partner,Cat,Intact Female,1 month,Domestic Shorthair Mix,Orange Tabby
26,A718832,Nia,2016-01-15 17:31:00,Adoption,NaN,Dog,Spayed Female,6 months,American Staffordshire Terrier Mix,Chocolate/White
27,A698777,Chloe,2015-03-25 18:50:00,Adoption,NaN,Dog,Spayed Female,5 years,Chihuahua Shorthair Mix,White/Tan
28,A715348,Cymbale,2015-11-21 13:01:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Cream Tabby/White
29,A708666,Jax,2015-07-30 14:30:00,Return_to_owner,NaN,Cat,Neutered Male,7 years,Russian Blue Mix,Blue
...,...,...,...,...,...,...,...,...,...,...
26699,A676460,Mario,2014-04-21 14:01:00,Euthanasia,Behavior,Dog,Neutered Male,2 years,American Pit Bull Terrier Mix,White/Black
26700,A704999,Lion,2015-06-15 19:28:00,Return_to_owner,NaN,Dog,Intact Male,10 months,Great Pyrenees/Anatol Shepherd,Tan/Cream
26701,A678842,Ella,2014-06-15 17:41:00,Transfer,Partner,Dog,Intact Female,11 months,Jack Russell Terrier Mix,White/Black
26702,A713637,NaN,2015-10-11 09:42:00,Died,In Kennel,Cat,Spayed Female,2 years,Siamese Mix,Lynx Point
26703,A716670,Mowmow,2015-12-04 12:22:00,Transfer,Partner,Cat,Neutered Male,6 years,Domestic Longhair Mix,Seal Point
26704,A716223,Alice,2015-11-17 17:17:00,Transfer,Partner,Cat,Intact Female,4 weeks,Domestic Shorthair Mix,White/Black
26705,A662498,Grace,2013-10-19 15:34:00,Transfer,Partner,Cat,Intact Female,2 months,Domestic Shorthair Mix,Tortie
26706,A689942,Zoey,2014-10-19 13:29:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Black
26707,A682690,NaN,2014-07-01 17:06:00,Euthanasia,Suffering,Cat,Unknown,1 year,Domestic Shorthair Mix,Brown Tabby
26708,A666920,Herbie,2013-11-13 17:32:00,Transfer,Partner,Dog,Neutered Male,2 years,Chihuahua Shorthair Mix,White/Brown
26709,A714386,NaN,2015-10-24 00:00:00,Adoption,NaN,Dog,Spayed Female,1 month,Chihuahua Shorthair Mix,Sable/Buff
26710,A692622,Bonnie,2014-11-24 17:21:00,Transfer,Partner,Dog,Intact Female,1 month,Chihuahua Shorthair/Yorkshire Terrier,Brown/Black
26711,A666284,Sonja,2013-10-30 18:32:00,Transfer,Partner,Dog,Intact Female,1 year,Cocker Spaniel/Dachshund,Buff
26712,A535277,Merlin,2015-04-20 16:04:00,Return_to_owner,NaN,Dog,Neutered Male,12 years,Rat Terrier,Chocolate/Tan
26713,A671169,NaN,2014-01-20 17:37:00,Euthanasia,Suffering,Cat,Intact Female,18 years,Domestic Longhair Mix,Tortie
26714,A679031,Pete,2014-05-31 16:11:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Orange Tabby
26715,A708833,Luna,2015-08-05 17:03:00,Adoption,NaN,Dog,Spayed Female,2 months,Pointer Mix,Black/White
26716,A697158,Max,2015-05-02 21:04:00,Adoption,Offsite,Dog,Neutered Male,2 months,Newfoundland Mix,White/Black
26717,A519949,Bella,2014-06-30 17:34:00,Return_to_owner,NaN,Dog,Spayed Female,9 years,Bullmastiff Mix,Black
26718,A701044,NaN,2015-04-28 14:26:00,Adoption,NaN,Dog,Neutered Male,2 months,Siberian Husky/German Shepherd,Black/Tricolor
26719,A707871,NaN,2015-07-20 09:00:00,Transfer,SCRP,Cat,Unknown,2 years,Domestic Shorthair Mix,Brown Tabby/White
26720,A704405,Brownie,2015-07-18 14:08:00,Adoption,NaN,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Brown Tabby
26721,A662019,Green Bean,2014-07-17 09:43:00,Adoption,Foster,Cat,Spayed Female,5 years,Domestic Shorthair Mix,Black
26722,A687056,NaN,2014-08-31 09:00:00,Transfer,SCRP,Cat,Intact Male,5 months,Domestic Shorthair Mix,Orange Tabby
26723,A716997,Zeus,2016-01-29 18:52:00,Adoption,NaN,Dog,Neutered Male,6 years,Staffordshire Mix,Blue/White
26724,A702446,NaN,2015-05-14 11:56:00,Transfer,Partner,Cat,Intact Male,1 month,Domestic Shorthair Mix,Brown Tabby/White
26725,A718934,NaN,2016-01-20 18:59:00,Transfer,SCRP,Cat,Spayed Female,3 months,Domestic Shorthair Mix,Brown Tabby
26726,A698128,Zeus,2015-03-09 13:33:00,Adoption,NaN,Dog,Neutered Male,4 years,Old English Bulldog Mix,White/Tan
26727,A677478,NaN,2014-04-27 12:22:00,Transfer,Partner,Cat,Intact Male,4 weeks,Domestic Shorthair Mix,Black
26728,A706629,NaN,2015-07-02 09:00:00,Transfer,SCRP,Cat,Intact Male,1 year,Domestic Shorthair Mix,Brown Tabby/White

In [108]:
test = pd.read_csv("./input/test.csv")
test

,ID,Name,DateTime,AnimalType,SexuponOutcome,AgeuponOutcome,Breed,Color
0,1,Summer,2015-10-12 12:15:00,Dog,Intact Female,10 months,Labrador Retriever Mix,Red/White
1,2,Cheyenne,2014-07-26 17:59:00,Dog,Spayed Female,2 years,German Shepherd/Siberian Husky,Black/Tan
2,3,Gus,2016-01-13 12:20:00,Cat,Neutered Male,1 year,Domestic Shorthair Mix,Brown Tabby
3,4,Pongo,2013-12-28 18:12:00,Dog,Intact Male,4 months,Collie Smooth Mix,Tricolor
4,5,Skooter,2015-09-24 17:59:00,Dog,Neutered Male,2 years,Miniature Poodle Mix,White
5,6,Beau,2015-06-23 11:17:00,Dog,Neutered Male,3 years,Beagle Mix,Brown/White
6,7,Bobo,2014-03-12 09:45:00,Cat,Neutered Male,13 years,Domestic Medium Hair Mix,Brown Tabby/White
7,8,Abby,2014-06-25 08:27:00,Cat,Spayed Female,6 months,Domestic Shorthair Mix,Brown Tabby
8,9,Ruby Grace,2014-11-12 18:05:00,Dog,Spayed Female,3 months,Cairn Terrier,Black/Cream
9,10,Ruby,2014-04-07 17:41:00,Dog,Spayed Female,1 year,Pit Bull Mix,Brown/White
10,11,Marlee,2014-01-01 17:03:00,Dog,Spayed Female,5 months,Labrador Retriever Mix,White/Black
11,12,Lala,2014-09-19 15:40:00,Dog,Intact Female,2 years,Pit Bull Mix,Blue/White
12,13,Chloe,2015-01-25 15:13:00,Dog,Spayed Female,6 months,Pit Bull Mix,Brown Brindle
13,14,NaN,2015-09-22 18:17:00,Dog,Neutered Male,2 years,Miniature Poodle Mix,White
14,15,Duffy,2014-07-20 19:24:00,Dog,Neutered Male,1 year,Flat Coat Retriever/German Shepherd,Black/Brown
15,16,Jiggy,2014-03-26 18:33:00,Dog,Spayed Female,4 months,Pointer/Labrador Retriever,White
16,17,Ghengis,2015-05-29 17:04:00,Dog,Neutered Male,5 years,Doberman Pinsch Mix,Black/Tan
17,18,Decker,2016-01-19 19:31:00,Dog,Neutered Male,3 years,English Bulldog,White/Tricolor
18,19,Freckles,2014-06-16 12:49:00,Cat,Spayed Female,3 years,Domestic Shorthair Mix,Torbie
19,20,NaN,2014-02-11 19:27:00,Cat,Intact Female,4 years,Domestic Shorthair Mix,Torbie
20,21,Pumpkin,2014-11-14 19:32:00,Cat,Spayed Female,2 years,Domestic Shorthair Mix,Black
21,22,NaN,2015-05-04 13:46:00,Cat,Unknown,3 weeks,Domestic Shorthair Mix,Black
22,23,Pluto,2014-06-07 14:14:00,Dog,Neutered Male,1 year,Norwich Terrier Mix,White/Tan
23,24,NaN,2014-07-20 15:37:00,Cat,Intact Female,1 week,Domestic Shorthair Mix,Tortie
24,25,Portia,2013-10-26 16:23:00,Dog,Spayed Female,1 year,Black Mouth Cur/Boxer,Tan
25,26,NaN,2014-12-29 13:10:00,Cat,Neutered Male,1 year,Domestic Shorthair Mix,Brown Tabby
26,27,Lucy,2015-07-23 16:18:00,Cat,Spayed Female,2 months,Domestic Medium Hair Mix,Black Smoke
27,28,NaN,2015-03-19 08:33:00,Dog,Intact Male,2 months,Norwich Terrier Mix,Brown
28,29,Jack,2014-10-09 17:22:00,Dog,Neutered Male,3 years,Labrador Retriever Mix,Black/White
29,30,Knight,2014-05-13 17:03:00,Dog,Neutered Male,2 years,Labrador Retriever Mix,Black
...,...,...,...,...,...,...,...,...
11426,11427,Fatboy,2013-12-28 14:22:00,Dog,Neutered Male,5 years,Boxer Mix,Brown/White
11427,11428,Calypso,2013-12-21 15:55:00,Dog,Intact Female,2 months,American Pit Bull Terrier Mix,Brown Brindle
11428,11429,Bolt,2013-11-15 12:32:00,Dog,Neutered Male,3 years,Siberian Husky,Red/White
11429,11430,Mary,2014-02-17 18:04:00,Dog,Spayed Female,2 years,German Shepherd Mix,Sable
11430,11431,NaN,2014-12-08 12:40:00,Cat,Spayed Female,2 months,Domestic Shorthair Mix,Blue
11431,11432,NaN,2015-06-30 09:00:00,Cat,Intact Male,2 years,Domestic Shorthair Mix,Blue Tabby/White
11432,11433,Fiona,2014-03-21 17:33:00,Dog,Spayed Female,5 years,Maltese,White
11433,11434,Evanna,2015-08-16 16:40:00,Cat,Intact Female,2 months,Domestic Shorthair Mix,Black/White
11434,11435,April,2015-09-06 12:41:00,Dog,Spayed Female,6 years,Cardigan Welsh Corgi/German Shepherd,Black/Tan
11435,11436,NaN,2015-08-13 17:09:00,Cat,Intact Male,3 weeks,Domestic Shorthair Mix,Brown Tabby
11436,11437,NaN,2014-03-21 17:42:00,Cat,Neutered Male,5 months,Domestic Shorthair Mix,Black/White
11437,11438,Peludita,2014-01-10 13:46:00,Dog,Intact Female,6 months,Chihuahua Longhair/Dachshund,White/Tan
11438,11439,NaN,2015-05-02 20:40:00,Dog,Neutered Male,1 month,Labrador Retriever Mix,Sable
11439,11440,Socks,2014-05-18 16:47:00,Dog,Spayed Female,2 years,Pit Bull Mix,White/Brown
11440,11441,NaN,2015-10-20 17:13:00,Cat,Unknown,1 week,Domestic Shorthair Mix,Brown Tabby
11441,11442,Doogie,2015-01-07 17:41:00,Dog,Neutered Male,4 years,Pit Bull Mix,Blue/White
11442,11443,Sterling,2015-11-28 16:23:00,Dog,Neutered Male,2 years,Chihuahua Shorthair Mix,Tan/White
11443,11444,Bella,2014-10-04 12:17:00,Cat,Spayed Female,6 months,Domestic Longhair Mix,Torbie
11444,11445,NaN,2014-06-01 17:15:00,Cat,Intact Female,2 years,Domestic Shorthair Mix,Calico
11445,11446,NaN,2015-04-14 14:34:00,Cat,Intact Male,2 weeks,Domestic Shorthair Mix,White
11446,11447,NaN,2015-07-19 20:03:00,Cat,Neutered Male,2 months,Domestic Shorthair Mix,Black
11447,11448,Sadie,2014-10-19 12:21:00,Dog,Spayed Female,1 year,Chihuahua Longhair Mix,Orange/Tan
11448,11449,NaN,2014-08-17 17:48:00,Dog,Spayed Female,2 months,Labrador Retriever Mix,Brown
11449,11450,Caicos,2015-07-20 14:55:00,Dog,Spayed Female,6 months,Bearded Collie Mix,Blue Merle/White
11450,11451,Cosmo,2015-11-05 17:19:00,Dog,Neutered Male,10 months,Staffordshire Mix,Tan/White
11451,11452,NaN,2014-07-08 14:50:00,Cat,Neutered Male,2 months,Domestic Shorthair Mix,Black
11452,11453,NaN,2014-10-21 12:57:00,Cat,Intact Female,2 weeks,Domestic Shorthair Mix,Blue
11453,11454,NaN,2014-09-29 09:00:00,Cat,Intact Female,1 year,Domestic Shorthair Mix,Calico
11454,11455,Rambo,2015-09-05 17:16:00,Dog,Neutered Male,6 years,German Shepherd Mix,Black/Tan
11455,11456,Gusto,2014-07-12 18:40:00,Dog,Intact Male,4 years,Labrador Retriever,Cream

In [109]:
#no columns have missing values
train.isnull().sum()

AnimalID              0
Name               7691
DateTime              0
OutcomeType           0
OutcomeSubtype    13612
AnimalType            0
SexuponOutcome        1
AgeuponOutcome       18
Breed                 0
Color                 0
dtype: int64

In [110]:
#Lets focus on each field one by one
#AnimalType
train['AnimalType'].value_counts()

Dog    15595
Cat    11134
Name: AnimalType, dtype: int64

In [111]:
def munge(data, train):
    data['HasName'] = data['Name'].fillna(0)
    data.loc[data['HasName'] != 0,"HasName"] = 1
    data['HasName'] = data['HasName'].astype(int)
    data['AnimalType'] = data['AnimalType'].map({'Cat':0,'Dog':1})

    if(train):
        data.drop(['AnimalID','OutcomeSubtype'],axis=1, inplace=True)
        data['OutcomeType'] = data['OutcomeType'].map({'Return_to_owner':4, 'Euthanasia':3, 'Adoption':0, 'Transfer':5, 'Died':2})
            
    gender = {'Neutered Male':1, 'Spayed Female':2, 'Intact Male':3, 'Intact Female':4, 'Unknown':5, np.nan:0}
    data['SexuponOutcome'] = data['SexuponOutcome'].map(gender)

    def agetodays(x):
        try:
            y = x.split()
        except:
            return None
        if 'year' in y[1]:
            return float(y[0]) * 365
        elif 'month' in y[1]:
            return float(y[0]) * (365/12)
        elif 'week' in y[1]:
            return float(y[0]) * 7
        elif 'day' in y[1]:
            return float(y[0])
        
    data['AgeInDays'] = data['AgeuponOutcome'].map(agetodays)
    data.loc[(data['AgeInDays'].isnull()),'AgeInDays'] = data['AgeInDays'].median()

    data['Year'] = data['DateTime'].str[:4].astype(int)
    data['Month'] = data['DateTime'].str[5:7].astype(int)
    data['Day'] = data['DateTime'].str[8:10].astype(int)
    data['Hour'] = data['DateTime'].str[11:13].astype(int)
    data['Minute'] = data['DateTime'].str[14:16].astype(int)

    data['Name+Gender'] = data['HasName'] + data['SexuponOutcome']
    data['Type+Gender'] = data['AnimalType'] + data['SexuponOutcome']
    data['IsMix'] = data['Breed'].str.contains('mix',case=False).astype(int)
            
    return data.drop(['AgeuponOutcome','Name','Breed','Color','DateTime'],axis=1)

train = munge(train,True)
train
test = munge(test,False)
test

,ID,AnimalType,SexuponOutcome,HasName,AgeInDays,Year,Month,Day,Hour,Minute,Name+Gender,Type+Gender,IsMix
0,1,1,4,1,304.166667,2015,10,12,12,15,5,5,1
1,2,1,2,1,730.000000,2014,7,26,17,59,3,3,0
2,3,0,1,1,365.000000,2016,1,13,12,20,2,1,1
3,4,1,3,1,121.666667,2013,12,28,18,12,4,4,1
4,5,1,1,1,730.000000,2015,9,24,17,59,2,2,1
5,6,1,1,1,1095.000000,2015,6,23,11,17,2,2,1
6,7,0,1,1,4745.000000,2014,3,12,9,45,2,1,1
7,8,0,2,1,182.500000,2014,6,25,8,27,3,2,1
8,9,1,2,1,91.250000,2014,11,12,18,5,3,3,0
9,10,1,2,1,365.000000,2014,4,7,17,41,3,3,1
10,11,1,2,1,152.083333,2014,1,1,17,3,3,3,1
11,12,1,4,1,730.000000,2014,9,19,15,40,5,5,1
12,13,1,2,1,182.500000,2015,1,25,15,13,3,3,1
13,14,1,1,0,730.000000,2015,9,22,18,17,1,2,1
14,15,1,1,1,365.000000,2014,7,20,19,24,2,2,0
15,16,1,2,1,121.666667,2014,3,26,18,33,3,3,0
16,17,1,1,1,1825.000000,2015,5,29,17,4,2,2,1
17,18,1,1,1,1095.000000,2016,1,19,19,31,2,2,0
18,19,0,2,1,1095.000000,2014,6,16,12,49,3,2,1
19,20,0,4,0,1460.000000,2014,2,11,19,27,4,4,1
20,21,0,2,1,730.000000,2014,11,14,19,32,3,2,1
21,22,0,5,0,21.000000,2015,5,4,13,46,5,5,1
22,23,1,1,1,365.000000,2014,6,7,14,14,2,2,1
23,24,0,4,0,7.000000,2014,7,20,15,37,4,4,1
24,25,1,2,1,365.000000,2013,10,26,16,23,3,3,0
25,26,0,1,0,365.000000,2014,12,29,13,10,1,1,1
26,27,0,2,1,60.833333,2015,7,23,16,18,3,2,1
27,28,1,3,0,60.833333,2015,3,19,8,33,3,4,1
28,29,1,1,1,1095.000000,2014,10,9,17,22,2,2,1
29,30,1,1,1,730.000000,2014,5,13,17,3,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11426,11427,1,1,1,1825.000000,2013,12,28,14,22,2,2,1
11427,11428,1,4,1,60.833333,2013,12,21,15,55,5,5,1
11428,11429,1,1,1,1095.000000,2013,11,15,12,32,2,2,0
11429,11430,1,2,1,730.000000,2014,2,17,18,4,3,3,1
11430,11431,0,2,0,60.833333,2014,12,8,12,40,2,2,1
11431,11432,0,3,0,730.000000,2015,6,30,9,0,3,3,1
11432,11433,1,2,1,1825.000000,2014,3,21,17,33,3,3,0
11433,11434,0,4,1,60.833333,2015,8,16,16,40,5,4,1
11434,11435,1,2,1,2190.000000,2015,9,6,12,41,3,3,0
11435,11436,0,3,0,21.000000,2015,8,13,17,9,3,3,1
11436,11437,0,1,0,152.083333,2014,3,21,17,42,1,1,1
11437,11438,1,4,1,182.500000,2014,1,10,13,46,5,5,0
11438,11439,1,1,0,30.416667,2015,5,2,20,40,1,2,1
11439,11440,1,2,1,730.000000,2014,5,18,16,47,3,3,1
11440,11441,0,5,0,7.000000,2015,10,20,17,13,5,5,1
11441,11442,1,1,1,1460.000000,2015,1,7,17,41,2,2,1
11442,11443,1,1,1,730.000000,2015,11,28,16,23,2,2,1
11443,11444,0,2,1,182.500000,2014,10,4,12,17,3,2,1
11444,11445,0,4,0,730.000000,2014,6,1,17,15,4,4,1
11445,11446,0,3,0,14.000000,2015,4,14,14,34,3,3,1
11446,11447,0,1,0,60.833333,2015,7,19,20,3,1,1,1
11447,11448,1,2,1,365.000000,2014,10,19,12,21,3,3,1
11448,11449,1,2,0,60.833333,2014,8,17,17,48,2,3,1
11449,11450,1,2,1,182.500000,2015,7,20,14,55,3,3,1
11450,11451,1,1,1,304.166667,2015,11,5,17,19,2,2,1
11451,11452,0,1,0,60.833333,2014,7,8,14,50,1,1,1
11452,11453,0,4,0,14.000000,2014,10,21,12,57,4,4,1
11453,11454,0,4,0,365.000000,2014,9,29,9,0,4,4,1
11454,11455,1,1,1,2190.000000,2015,9,5,17,16,2,2,1
11455,11456,1,3,1,1460.000000,2014,7,12,18,40,4,4,0

In [ ]:
test.drop('ID',inplace=True,axis=1)

tr = train.values
te = test.values

print("Calculating best case params...\n")

def best_params(data):
    rfc = RandomForestClassifier()
    param_grid = { 
        'n_estimators': [50, 400],
        'max_features': ['auto', 'sqrt', 'log2']
    }
    
    CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
    CV_rfc.fit(data[0::,1::],data[0::,0])
    return CV_rfc.best_params_

print(best_params(tr))

In [ ]:
print("Predicting... \n")
forest = RandomForestClassifier(n_estimators = 400, max_features='auto')
forest = forest.fit(tr[0::,1::],tr[0::,0])
predictions = forest.predict_proba(te)

output = pd.DataFrame(predictions,columns=['Adoption','Died','Euthanasia','Return_to_owner','Transfer'])
output.columns.names = ['ID']
output.index.names = ['ID']
output.index += 1

print("Writing predictions.csv\n")
print(output)
output.to_csv('predictions.csv')
print("Done.\n")